### ISSUE TITLE
the agent.py is missing in module-3/studio

### ISSUE THREAD

**Issue by RedouanAssakali** [langchain-ai/langchain-academy#10]
The agent.py that is used in the tutorial is missing in module-3/studio

**Comment by rlancemartin** [comment]
Thanks! Ntbks said to use agent.py from Module 1, but I agree that it's nice just to have this in Module 3 in case users have already loaded that directory in Studio. Resolved! 
https://github.com/langchain-ai/langchain-academy/commit/0791a4ba2d933bc8e57f6d8c993b9d3b77cfa35d
