### ISSUE TITLE
suggested minor content change in module 1

### ISSUE THREAD

**Issue by robbiemu** [langchain-ai/langchain-academy#12]
I created this [PR](https://github.com/langchain-ai/langchain-academy/pull/11) because I have a content change I'd like to suggest as well, and when I did my pip install I had suddenly 12k changes. It is just a `.gitignore` enhancement to exclude operating system and pip caches to make it easier to add PRs.

I should discuss the intended change before adding that PR as well, especially as I do not have a funded OPEN_API_KEY to rely on.

## the issue

In module1/chain.lypnb this call:

```py
tool_call.additional_kwargs['tool_calls']
```

fails if we try to follow along by replacing the model for a local one:
```py
from langchain_ollama import ChatOllama

llm = ChatOllama(
    model = "llama3.1:8b-instruct-q8_0",
    temperature = 0.8,
    num_ctx=4096,
    num_predict = 4096,
)
result = llm.invoke(messages)
type(result)
```

the response in my case is:
```py
AIMessage(content='', response_metadata={'model': 'llama3.1:8b-instruct-q8_0', 'created_at': '2024-09-12T00:46:15.444888Z', 'message': {'role': 'assistant', 'content': '', 'tool_calls': [{'function': {'name': 'multiply', 'arguments': {'a': '2', 'b': '3'}}}]}, 'done_reason': 'stop', 'done': True, 'total_duration': 1123354500, 'load_duration': 33275917, 'prompt_eval_count': 163, 'prompt_eval_duration': 538668000, 'eval_count': 22, 'eval_duration': 550083000}, id='run-3b044993-c4dc-46de-affc-c9de5502e4d1-0', tool_calls=[{'name': 'multiply', 'args': {'a': '2', 'b': '3'}, 'id': '2990ef78-d2dc-4f1f-aa06-04b786a2bf3f', 'type': 'tool_call'}], usage_metadata={'input_tokens': 163, 'output_tokens': 22, 'total_tokens': 185})
```

so additional_kwargs is empty, we see instead:
```
{
	"name": "KeyError",
	"message": "'tool_calls'",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[13], line 1
----> 1 tool_call.additional_kwargs['tool_calls']

KeyError: 'tool_calls'"
}
```
and we don't see:
```py
[{'id': 'call_OP4qwtGk4gTIaIySPFHkpbB2',
  'function': {'arguments': '{"a":2,"b":3}', 'name': 'multiply'},
  'type': 'function'}]
```
but if we change it to `tool_call.tool_calls` we will see the missing information:
```py
[{'name': 'multiply',
  'args': {'a': '2', 'b': '3'},
  'id': '2990ef78-d2dc-4f1f-aa06-04b786a2bf3f',
  'type': 'tool_call'}]
```

I hesitate to immediately make this change in a PR without discussing it first because the response body that I get back, from my local model, does not look the same, and the id's in the results don't have similar shape. Perhaps it would be better for someone with funding in open ai api to make the change.

**Comment by robbiemu** [comment]
a second suggestion, in module 4, research assistant, some models will not respond if the final message in the conversation is an AIMessage (which is always the case), so you may have to modify search_wikipedia and search_web to "humanize" the last message like:
`msg = HumanMessage(content=msg.content)`. This is true for local models but may even be true for non gpt models (When I run mistral-nemo locally, it will not respond. If you have a ChatMistral, that would behave the same way).

**Comment by rlancemartin** [comment]
> I created this [PR](https://github.com/langchain-ai/langchain-academy/pull/11) because I have a content change I'd like to suggest as well, and when I did my pip install I had suddenly 12k changes. It is just a `.gitignore` enhancement to exclude operating system and pip caches to make it easier to add PRs.
> 
> I should discuss the intended change before adding that PR as well, especially as I do not have a funded OPEN_API_KEY to rely on.
> 
> ## the issue
> In module1/chain.lypnb this call:
> 
> ```python
> tool_call.additional_kwargs['tool_calls']
> ```
> 
> fails if we try to follow along by replacing the model for a local one:
> 
> ```python
> from langchain_ollama import ChatOllama
> 
> llm = ChatOllama(
>     model = "llama3.1:8b-instruct-q8_0",
>     temperature = 0.8,
>     num_ctx=4096,
>     num_predict = 4096,
> )
> result = llm.invoke(messages)
> type(result)
> ```
> 
> the response in my case is:
> 
> ```python
> AIMessage(content='', response_metadata={'model': 'llama3.1:8b-instruct-q8_0', 'created_at': '2024-09-12T00:46:15.444888Z', 'message': {'role': 'assistant', 'content': '', 'tool_calls': [{'function': {'name': 'multiply', 'arguments': {'a': '2', 'b': '3'}}}]}, 'done_reason': 'stop', 'done': True, 'total_duration': 1123354500, 'load_duration': 33275917, 'prompt_eval_count': 163, 'prompt_eval_duration': 538668000, 'eval_count': 22, 'eval_duration': 550083000}, id='run-3b044993-c4dc-46de-affc-c9de5502e4d1-0', tool_calls=[{'name': 'multiply', 'args': {'a': '2', 'b': '3'}, 'id': '2990ef78-d2dc-4f1f-aa06-04b786a2bf3f', 'type': 'tool_call'}], usage_metadata={'input_tokens': 163, 'output_tokens': 22, 'total_tokens': 185})
> ```
> 
> so additional_kwargs is empty, we see instead:
> 
> ```
> {
> 	"name": "KeyError",
> 	"message": "'tool_calls'",
> 	"stack": "---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> Cell In[13], line 1
> ----> 1 tool_call.additional_kwargs['tool_calls']
> 
> KeyError: 'tool_calls'"
> }
> ```
> 
> and we don't see:
> 
> ```python
> [{'id': 'call_OP4qwtGk4gTIaIySPFHkpbB2',
>   'function': {'arguments': '{"a":2,"b":3}', 'name': 'multiply'},
>   'type': 'function'}]
> ```
> 
> but if we change it to `tool_call.tool_calls` we will see the missing information:
> 
> ```python
> [{'name': 'multiply',
>   'args': {'a': '2', 'b': '3'},
>   'id': '2990ef78-d2dc-4f1f-aa06-04b786a2bf3f',
>   'type': 'tool_call'}]
> ```
> 
> I hesitate to immediately make this change in a PR without discussing it first because the response body that I get back, from my local model, does not look the same, and the id's in the results don't have similar shape. Perhaps it would be better for someone with funding in open ai api to make the change.

Got it. I haven't tested all the content to ensure that it works w/ local LLMs. 

This was out of scope, unfortunately, because [tool-calling with local (8b) models](https://python.langchain.com/docs/how_to/tool_calling/) if often highly degraded vs SOTA models (sonnet, 4o) and the aim here is the highlight the concepts. 

I did a bit of work on this w/ [@GroqInc](https://x.com/GroqInc) fine-tune-8b, but in general 8b is a small capacity model for reliable tool calling. 

https://x.com/RLanceMartin/status/1816869550035763663

**Comment by rlancemartin** [comment]
> a second suggestion, in module 4, research assistant, some models will not respond if the final message in the conversation is an AIMessage (which is always the case), so you may have to modify search_wikipedia and search_web to "humanize" the last message like: `msg = HumanMessage(content=msg.content)`. This is true for local models but may even be true for non gpt models (When I run mistral-nemo locally, it will not respond. If you have a ChatMistral, that would behave the same way). Likewise the quality will be a lot lower if we do not do the same for generate_answer, as its references will be intact but no write up will be done by the expert

Going to open a new issue for this.
