### ISSUE TITLE
ChatOpenAI model calls functions in parallel, not sequentially (Module 1 - Lesson 6: Agent)

### ISSUE THREAD

**Issue by labdmitriy** [langchain-ai/langchain-academy#14]
Hi @rlancemartin,

Thanks a lot for this amazing course!

I found that if we use the example you provided to add, multiply and divide numbers, the result is not calculated sequentially, so all 3 tools are called in parallel and it seems that LLM uses internal knowledge, not specified tools, to calculate intermediate results.

We can check it using more complex example:
`Add 302 and 42, then multiply by 12, and finally divide by 35`
(302 + 42) * 12 / 35 = 117.94285714285714 

And in this case we will get the wrong result, probably because it is much more complex task for LLM itself to calculate all intermediate results correctly without tools (I am using 'gpt-4o-mini' for the experiments):
```
================================ Human Message =================================

Add 302 and 42, then multiply by 12, and finally divide by 35
================================== Ai Message ==================================
Tool Calls:
  add (call_hZBa8efjuRWQ9117qqG67Bxh)
 Call ID: call_hZBa8efjuRWQ9117qqG67Bxh
  Args:
    a: 302
    b: 42
  multiply (call_KxItYR2ZPQllT0lGcwYmfg7A)
 Call ID: call_KxItYR2ZPQllT0lGcwYmfg7A
  Args:
    a: 302
    b: 12
  divide (call_wmFM6Cr57lFjWtR0nec3vBud)
 Call ID: call_wmFM6Cr57lFjWtR0nec3vBud
  Args:
    a: 12
    b: 35
================================= Tool Message =================================
Name: divide

0.34285714285714286
================================== Ai Message ==================================
Tool Calls:
  divide (call_oAO56pB0Bdwn3bxq5VBh4c01)
 Call ID: call_oAO56pB0Bdwn3bxq5VBh4c01
  Args:
    a: 3624
    b: 35
================================= Tool Message =================================
Name: divide

103.54285714285714
================================== Ai Message ==================================

The final result after adding 302 and 42 (which gives 344), multiplying by 12 (resulting in 3624), and then dividing by 35 is approximately **103.54**.
```

So we can see that LLM tries to call 3 functions in parallel with weird arguments, so we've got incorrect results and only one iteration of the loop.

But if we turn off parallel tool calling while binding tools (using `llm.bind_tools(tools, parallel_tool_calls=False)`), then we will have 3 iterations of the loop and correct both intermediate and final results:
```
================================ Human Message =================================

Add 302 and 42, then multiply by 12, and finally divide by 35
================================== Ai Message ==================================
Tool Calls:
  add (call_erKrB65cFumaZOcs565yD5cg)
 Call ID: call_erKrB65cFumaZOcs565yD5cg
  Args:
    a: 302
    b: 42
================================= Tool Message =================================
Name: add

344
================================== Ai Message ==================================
Tool Calls:
  multiply (call_Y3QgNjPTClmQ6c0SEs4OKAKD)
 Call ID: call_Y3QgNjPTClmQ6c0SEs4OKAKD
  Args:
    a: 344
    b: 12
================================= Tool Message =================================
Name: multiply

4128
================================== Ai Message ==================================
Tool Calls:
  divide (call_BHswd0HVlulGD82R95LBMDVL)
 Call ID: call_BHswd0HVlulGD82R95LBMDVL
  Args:
    a: 4128
    b: 35
================================= Tool Message =================================
Name: divide

117.94285714285714
================================== Ai Message ==================================

The final result after adding 302 and 42, multiplying by 12, and then dividing by 35 is approximately 117.94.
```

Thank you.

**Comment by robbiemu** [comment]
I thought this same issue was because I am using a local model instead of OpenAI API :) 
I thought this was a little awkward but found prepending this instruction resolved the issue "Perform each step with a tool, one after another."

In the graph, I see "called" on each of the three, and they each have a tool call that happens in order.

**Comment by rlancemartin** [comment]
Yes, this is a good call-out! @shiv248 addressed with `parallel_tool_calls=False` in the attached PR.
