### ISSUE TITLE
Error in Getting Setup

### ISSUE THREAD

**Issue by AIHypnosis** [langchain-ai/langchain-academy#18]
Error running: **source lc-academy-env/bin/activate**
`PS C:\Users\User\Documents\AI\LangGraph\langchain-academy> source lc-academy-env/bin/activate
source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ source lc-academy-env/bin/activate
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

I am on Windows, Python 3.12.4
Is there something missing in your Setup instructions?
Should the command be: **lc-academy-env/Scripts/activate** for PC users?

**Comment by shiv248** [comment]
good catch, for PC try:
```
PS$ python3 -m venv lc-academy-env
PS$ Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
PS$ lc-academy-env\scripts\activate
PS$ pip install -r requirements.txt
```
from [https://forum.freecodecamp.org/t/cannot-activate/557438/11](https://forum.freecodecamp.org/t/cannot-activate/557438/11)

cc @rlancemartin LC-A has venv setup for mac only, windows venv isn't listed

**Comment by shiv248** [comment]
@AIHypnosis also would recommend using Windows WSL if you can, it alleviates a lot of hurdles you might face from an environment perspective in a developer setting.

**Comment by rlancemartin** [comment]
Ah, got it! @shiv248 do you want to put up a PR that adds this to the README?

**Comment by shiv248** [comment]
will do! I'll combine it with a couple other issues that were brought up and make a pr!
