### ISSUE TITLE
[Bug] Streaming on Colab not working

### ISSUE THREAD

**Issue by shiv248** [langchain-ai/langchain-academy#2]
### Info
Hello!

I noticed the streaming through Google Colab isn't working, have described it below.
### Description
Current output:
![Recording 2024-09-08 at 05 04 06](https://github.com/user-attachments/assets/eebc289a-a227-4aa0-9b9f-ba0ef5019ee4)

Expected output:
![Recording 2024-09-08 at 05 07 25](https://github.com/user-attachments/assets/5a9877ff-6537-4b4c-a874-b51e4899a9ff)

### Potential Fix
The issue is due Google Colab being at on python 3.10.
<img width="380" alt="image" src="https://github.com/user-attachments/assets/58f6c4a0-f7fa-4751-9548-77cfd65a65d9">

Fix is using RunnableConfig.
https://langchain-ai.github.io/langgraph/how-tos/streaming-tokens/#:~:text=Note%20on%20Python%20%3C%203.11

### System Info
Using latest version of Google Colab, Version 2024-08-20

**Comment by rlancemartin** [comment]
Good catch! Added this to default ntbk. 
https://github.com/langchain-ai/langchain-academy/commit/84259c04f9c83d7dae9f47c46ff1d4a68d8b67c6
