### ISSUE TITLE
Accidental 3 factorial in Module 1, chain.ipynb

### ISSUE THREAD

**Issue by jekriske-lilly** [langchain-ai/langchain-academy#22]
https://github.com/langchain-ai/langchain-academy/blob/main/module-1/chain.ipynb

In the very last cell
```
messages = graph.invoke({"messages": HumanMessage(content="Multiply 2 and 3!")})
for m in messages['messages']:
    m.pretty_print()
```

Whiles this works fine for gpt-4o currently, if you pass the same string to gpt-4o-mini it takes the 3! as 3 factorial and thus generates:

```
================================ Human Message =================================

Multiply 2 and 3!
================================== Ai Message ==================================
Tool Calls:
  multiply (call_cHFQvscUcATP5EAVp8yequyl)
 Call ID: call_cHFQvscUcATP5EAVp8yequyl
  Args:
    a: 2
    b: 6
```

I'd recommend the exclamation point be changed to a period for consistency across models.

**Comment by shiv248** [comment]
this is such an interesting find haha. i like it.

**Comment by rlancemartin** [comment]
Fixed with https://github.com/langchain-ai/langchain-academy/pull/32 ... interesting bug!
