### ISSUE TITLE
Messages are not trimmed before graph invocation (Module 2 - Lesson 4: Trim and Filter Messages)

### ISSUE THREAD

**Issue by labdmitriy** [langchain-ai/langchain-academy#24]
Hi @rlancemartin,

You have an example of message trimming:
```python
trim_messages(
            messages,
            max_tokens=100,
            strategy="last",
            token_counter=ChatOpenAI(model="gpt-4o-mini"),
            allow_partial=False
        )
```
But the result is not saved so the following code uses full history of messages without message trimming:
```python
# Invoke, using message trimming
messages_out_trim = graph.invoke({'messages': messages})
```
Thank you.

**Comment by robbiemu** [comment]
a problem that feels related, but really isn't but still it feels the same, appears in the research assistant, where we generate up to 3, wait for human feedback, which asks for one more, we specify it as our HF, then continue, which reruns the previous so we get both the new one that was specified and a few more.

**Comment by rlancemartin** [comment]
see the `chat_model_node`. 

it includes `trim_messages`. 

so, the trimming is applied to messages before `return {"messages": [llm.invoke(messages)]}`.

`# Invoke, using message trimming` is applied in the `chat_model_node`. 

i will update the comment to clarify this.

**Comment by rlancemartin** [comment]
See here:
https://github.com/langchain-ai/langchain-academy/commit/8cca5e1092d01931f6aa9143ffc87d21ccd6052f

Also you are welcome to put up a PR if further clarification is helpful!

**Comment by labdmitriy** [comment]
Thank you!
