### ISSUE TITLE
Incorrect agent is used for new thread in LangGraph Studio (Module 2 - Lesson 6: Chatbot w/ Summarizing Messages and External Memory)

### ISSUE THREAD

**Issue by labdmitriy** [langchain-ai/langchain-academy#25]
Hi @rlancemartin,

I noticed that when you switched to the new thread in LangGraph Studio, you checked the persistence not using summarization chatbot but the agent from Module 1 (starting from 6:54).
Could you please tell are there any plans to use the last graph while creating a new thread instead of switching to another thread each time?

Thank you.

**Comment by rlancemartin** [comment]
ah, this is a good catch. 

here is what happened -- 

1/ when i filmed, i had all of the graphs in a single folder.
2/ when you create a new thread, it defaults to the **first graph** in your graph list (alphabetically).
3/ in this case, that first graph was `agent` from Module 1.

in your case, it will just show `chatbot` when you create a new thread b/c that is the only graph in the module 2 folder.

i may re-film if this causes concern.

the central point is to show returning to a previous thread, which hopefully it does clearly.

**Comment by labdmitriy** [comment]
Thank you!
