### ISSUE TITLE
[Enhancement] Colab accessibility for external memory ipynb

### ISSUE THREAD

**Issue by shiv248** [langchain-ai/langchain-academy#3]
### Info
Hello!

As Google Colab is a viable option of a usable platform through the course, the `chatbot-external-memory.ipynb` unfortunately is cut short if a user is learning via that avenue.

### Description
<img width="808" alt="image" src="https://github.com/user-attachments/assets/e088cde9-4902-4007-a48b-97f8461ee2ba">

If user skips this cell, it causes waterfall issues for the following cells in turn a colab user can't follow along for this lesson.

### Potential Fix
As file is hosted on GitHub, can be fixed by using [`wget`](https://www.gnu.org/software/wget/). Though potentially could be a broken step if the parent_dir/files are changed from GitHub.

### System Info
Using latest version of Google Colab, Version 2024-08-20

**Comment by rlancemartin** [comment]
Yes. 

In general, for users that want full functionality I'd advise running notebooks locally and not using CoLab.
