### ISSUE TITLE
[Enhancement] ipynb Navigation

### ISSUE THREAD

**Issue by shiv248** [langchain-ai/langchain-academy#5]
### Info
Hello!

Working through the course, I got frustrated trying to understand which module and file I was working under when I was jumping around my files. Also within a module felt lost about which lesson I'm currently working on and which is next.
### Description
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/9ed964c8-f1cb-4a53-bbc0-66b1487dbfc1">

<img width="304" alt="image" src="https://github.com/user-attachments/assets/99987201-c344-4a40-8d07-7af4ab3bcb4a">

### Potential Fix
relabel files

### Platform
NA

**Comment by shiv248** [comment]
maybe I misunderstood, do you mean for each GitHub and Colab file link to the LangChain Academy video? or under each video link to the GitHub and Colab file?

**Comment by jessicaou** [comment]
Unfortunately when adding links to the bottom of the video page, the platform we use reduces the size of the video significantly to where the text becomes much harder to read (and is unable to be resized. only option is to make the video full screen which is not desirable for learners), so this is a platform limitation. We do have the notebook names listed in the module resources, but I understand that might not be the most convenient.

**Comment by shiv248** [comment]
@jessicaou ah, that is a tough one if there is a platform limitation for that approach, how about splitting up the resources to be directly underneath each module? It would make it convenient from the LangChain Academy users perspective, like this:
<img width="392" alt="image" src="https://github.com/user-attachments/assets/d23aa6b7-e6ce-4282-8b7a-0c32a90e747a">
Though it could get cluttered and might look daunting at first glance of "12 Lessons" to go through for this Module due to the additional `text` content, even more for bigger Modules.

**Comment by rlancemartin** [comment]
[Badges](https://github.com/langchain-ai/langchain-academy/pull/19) were a great addition to aid navigation!
