### ISSUE TITLE
Module 5 Studio Crash: Incorrect Filename References in langgraph.json

### ISSUE THREAD

**Issue by mjunaidca** [langchain-ai/langchain-academy#58]
Found this while working on Module 5 - Studio was crashing due to incorrect filenames in langgraph.json.

## Bug Report
LangGraph Studio crashes when running Module 5 due to incorrect filename references in langgraph.json.

## Details
- Location: `Module 5/studio/langgraph.json`
- Problem: Graph keys use `chatbot_*` prefix while actual files use `memory_*` pattern
- Impact: Studio fails to locate files, preventing learners from proceeding

**Comment by mjunaidca** [comment]
Hi @rlancemartin @jessicaou

Found this while working on Module 5 - Studio was crashing due to incorrect filenames in langgraph.json. PR submitted with fix: #57

**Comment by rlancemartin** [comment]
Fixed! Thanks for the PR. Filenames got changed last minute.
